name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@main
        env:
          ACCESS_TOKEN: ${{ secrets.BLOG_TOKEN }}
          TARGET_REPO: SUN-TN/blogs
          TARGET_BRANCH: blogs
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist